### ISSUE TITLE
Agradecimientos

### ISSUE THREAD

**Issue by SebaG20xx** [benjarojas/autoRut.py#1]
Debido a que no ví forma de contacto en tu perfil de GitHub jaja, te escribo para agradecerte, usé parte de tu código en un bot que creé para discord que realiza las consultas directas a la página, agradecido.

**Comment by benjarojas** [comment]
Buenisimaa, me alegro que te haya servido el script! Ah y gracias por avisar, desde ahora dejaré mi correo en mi perfil xD

**Comment by SebaG20xx** [comment]
Tristemente agregaron Cloudflare y ahora pide captcha xD, haré algo de research para ver si encuentro como hacer bypass
